server:
  port: 587

rabbitmq:
  exchangeName: thanhnt.exchange
  user-mail-queue: userMailQueue
  user-mail-routing-key: userMailQueueRoutingKey
  store-mail-queue: storeMailQueue
  store-mail-routing-key: storeMailQueueRoutingKey

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
    exposure:
      include: '*'
  endpoint:
    health:
      show-details: always

logging:
    level:
        root: WARN
        com.thanhnt.mailservice: INFO