eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/orderservice
    username: orderservice
    password: 12345

  data:
    redis-order:
      host: localhost
      port: 6379
      database: 3
    redis-shop:
      host: localhost
      port: 6379
      database: 1