eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db-postgresql-order:5437/orderservice
    username: ${DB_USERNAME_ORDER}
    password: ${DB_PASSWORD_ORDER}

  data:
    redis-order:
      host: redis-stack-ecommerce
      port: 6379
      database: 3
    redis-shop:
      host: redis-stack-ecommerce
      port: 6379
      database: 1