spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

management:
  endpoints:
    web:
    exposure:
      include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    com.thanhnt.eurekaserver: INFO