server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    discovery:
      enabled: true
  application:
    name: store-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

rabbitmq:
  exchangeName: thanhnt.exchange
  store-mail-queue: storeMailQueue
  store-mail-routing-key: storeMailQueueRoutingKey


service:
  external:
    timeout: 60000

thanhnt:
  defaultAvatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/User-avatar.svg/2048px-User-avatar.svg.png"
  shopCacheKey: "SHOP_CACHE_OF_USER_"

management:
  endpoints:
    web:
    exposure:
      include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    com.thanhnt.storeservice: INFO